### ISSUE TITLE
wideresnet object has no attribute 'model'

### ISSUE THREAD

**Issue by HoJ00n2** [mariodoebler/test-time-adaptation#2]
Hello, I'm glad to hear that you found my paper interesting. 
Regarding the error I encountered while running the code, 
even though I followed the instructions in the readme and made sure the virtual environment version matches, 

err message is..

Traceback (most recent call last):
  File "/root/workspace/code/rmt/classification/test_time.py", line 483, in <module>
    evaluate('"Evaluation.')
  File "/root/workspace/code/rmt/classification/test_time.py", line 78, in evaluate
    model, param_names = setup_rmt(base_model, num_classes)
  File "/root/workspace/code/rmt/classification/test_time.py", line 409, in setup_rmt
    rmt_model = RMT(model, optimizer,
  File "/root/workspace/code/rmt/classification/methods/rmt.py", line 54, in __init__
    self.feature_extractor, self.classifier = split_up_model(model, arch_name, self.dataset_name)
  File "/root/workspace/code/rmt/classification/models/model.py", line 313, in split_up_model
    if hasattr(model.model, model.model.pretrained_cfg["classifier"]):
  File "/root/anaconda3/envs/rmt/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'WideResNet' object has no attribute 'model'

could you please provide more information about the error message and what step you were trying to execute?

best

**Comment by RobMarsden** [comment]
Hello HoJ00n2,
thank you very much for pointing out the bug. It's fixed now.
Out of curiosity, which paper is yours?
Best,
Rob

**Comment by HoJ00n2** [comment]
thank you for your notice!

oh I'm sorry first line's  "my paper" is mistake.
I mean your paper is very interesting!
